name: psgc_picker
description: This package is used for listing all the region, province, city, municipality, and barangay. Philippine Standard Geographic Codes
version: 0.0.2
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  assets:
    - lib/src/assets/
